// <auto-generated />
namespace WebBookingCare.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _19_05 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_19_05));
        
        string IMigrationMetadata.Id
        {
            get { return "202305190437035_19_05"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
